In [1]:
import numpy as np

In [2]:
np.mean([2, 4, 5, 6])

4.25

In [3]:
np.median([2, 4, 5, 6])

4.5

In [4]:
np.std([2, 4, 5, 6])

1.479019945774904

In [5]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [6]:
import pandas as pd

In [15]:
sample_data = {"name": ["Ray", "Steph", "Michael", "Tim", "Durant", "Westbrook"],
               "power": ["average", "unbelievable", "best_ever", "stellar", "average", "stellar"]}

data = pd.DataFrame(sample_data, columns = ["name", "power"])

In [16]:
label_encoder = LabelEncoder()
label_encoder.fit(data['power'])

LabelEncoder()

In [17]:
label_encoder.classes_

array(['average', 'best_ever', 'stellar', 'unbelievable'], dtype=object)

In [19]:
label_encoder.transform(data['power'])

array([0, 3, 1, 2, 0, 2], dtype=int64)

In [20]:
one_hot_encoder = OneHotEncoder()
one_hot_encoder.fit(data['power'])

ValueError: could not convert string to float: stellar

In [22]:
pd.get_dummies(data['power'])

average  best_ever  stellar  unbelievable
0        1          0        0             0
1        0          0        0             1
2        0          1        0             0
3        0          0        1             0
4        1          0        0             0
5        0          0        1             0

In [24]:
one_hot_encoder.fit(pd.get_dummies(data['power']))

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [27]:
one_hot_encoder.feature_indices_

array([0, 2, 4, 6, 8])

In [29]:
one_hot_encoder.transform(pd.get_dummies(data['power'])).toarray()

array([[ 0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.]])

In [31]:
label_encoded_data = label_encoder.fit_transform(data['power'])

In [34]:
ohe = one_hot_encoder.fit_transform(label_encoded_data.reshape(-1, 1)).toarray()

In [35]:
pd.DataFrame(ohe, columns = label_encoder.classes_)

average  best_ever  stellar  unbelievable
0      1.0        0.0      0.0           0.0
1      0.0        0.0      0.0           1.0
2      0.0        1.0      0.0           0.0
3      0.0        0.0      1.0           0.0
4      1.0        0.0      0.0           0.0
5      0.0        0.0      1.0           0.0