In [1]:
import tensorflow as tf

In [2]:
first_constant = tf.constant("First Constant!")

with tf.Session() as sess:
    output = sess.run(first_constant)
    print(output)

b'First Constant!'


In [3]:
def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        output = sess.run(x, feed_dict={x: 123})

    return output

run()

array(123)

In [14]:
x = tf.placeholder(tf.float32)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x:tf.divide(15,4)})
    
output

array(3.75, dtype=float32)

In [25]:
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    x = tf.constant(10)
    y = tf.constant(2)
    z = tf.divide(x,y) - 1
    output = sess.run(z)
    
output

4.0

In [32]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x ,y), tf.cast(tf.constant(1), tf.float64))

with tf.Session() as sess:
    output = sess.run(z)

In [33]:
output

4.0

In [34]:
z

<tf.Tensor 'Sub_4:0' shape=() dtype=float64>

In [35]:
x

<tf.Tensor 'Const_25:0' shape=() dtype=int32>

In [36]:
tf.constant(1)

<tf.Tensor 'Const_28:0' shape=() dtype=int32>

In [37]:
tf.divide(x, y)

<tf.Tensor 'truediv_8:0' shape=() dtype=float64>

In [38]:
x = tf.nn.softmax([1.5, 2.9, 8.7])

In [39]:
x

<tf.Tensor 'Reshape_1:0' shape=(3,) dtype=float32>

In [44]:
with tf.Session() as sess:
    output = sess.run(x)

In [45]:
output

array([  7.43778830e-04,   3.01617198e-03,   9.96240020e-01], dtype=float32)

In [48]:
x = tf.nn.softmax([4.6, 4.5, 4.8])
tf.Session().run(x)

array([ 0.31987301,  0.28943309,  0.39069387], dtype=float32)

In [50]:
tf.Session().run(tf.nn.softmax([2.0, 1.0, 0.1]))

array([ 0.65900117,  0.24243298,  0.09856589], dtype=float32)

In [51]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

In [52]:
n_input = 784 
n_classes = 10

mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /datasets/ud730/mnist\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /datasets/ud730/mnist\train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /datasets/ud730/mnist\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /datasets/ud730/mnist\t10k-labels-idx1-ubyte.gz


In [57]:
import numpy as np
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

weights= tf.Variable(tf.truncated_normal([n_input, n_classes]))
bias = tf.Variable(tf.truncated_normal([n_classes]))

In [58]:
train_features.shape

(55000, 784)

In [61]:
train_features

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [62]:
5%3

2

In [64]:
5 / 3

1.6666666666666667

In [65]:
import numpy as np

In [66]:
x = np.array([[0,0,1], [1,1,1], [1, 0, 1], [0, 1, 1]])
y = np.array([[0, 0, 1, 1]]).T
syn0 = np.random.random((3,4)) - 1
syn1 = np.random.random((4,1)) - 1

In [67]:
syn0.shape

(3, 4)

In [68]:
y.shape

(4, 1)

In [69]:
l1 = 1 / 1 +np.exp(-np.dot(x, syn0))

In [70]:
l1.shape

(4, 4)

In [71]:
l2 = 1/ 1 + np.exp(-np.dot(l1, syn1))

In [75]:
delta_l2 = (y - l2) * l2 * (1-l2)

In [76]:
delta_l1 = delta_l2.dot(syn1.T) * (l1 * (1-l1))

In [77]:
syn1 += l1.T.dot(delta_l2)
syn0 += x.T.dot(delta_l1)

In [78]:
syn1.shape

(4, 1)

In [79]:
syn0.shape

(3, 4)

In [80]:
l2

array([[  2.61498044e+02],
       [  1.55925596e+06],
       [  8.20639505e+03],
       [  3.62523937e+03]])

In [89]:
for j in range(50000):
    l1 = 1/ (1 + np.exp(-np.dot(x, syn0)))
    l2 = 1/ (1 + np.exp(-np.dot(l1, syn1)))
    l2_delta = (y - l2) * (l2 * (1 - l2))
    l1_delta = l2_delta.dot(syn1.T) * l1 * (1 - l1)
    syn1 += l1.T.dot(l2_delta)
    syn0 += x.T.dot(l1_delta)

In [90]:
syn0

array([[  4.79782432e+18,   4.24886877e+19,   2.23218709e+20,
          6.14795883e+19],
       [  4.79782371e+18,   4.24886829e+19,   2.23218703e+20,
          6.14795864e+19],
       [  4.79782435e+18,   4.24886879e+19,   2.23218710e+20,
          6.14795885e+19]])

In [91]:
syn1

array([[  9.91051079e+18],
       [  1.49471137e+19],
       [  3.35900174e+19],
       [  3.20400016e+19]])

In [92]:
l2

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [93]:
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])


In [106]:
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_output = tf.nn.relu(hidden_layer)

output_output = tf.add(tf.matmul(hidden_output, weights[1]) , biases[1])
# output_output = tf.nn.relu(output_layer)

output_output

<tf.Tensor 'Add_9:0' shape=(3, 2) dtype=float32>

In [107]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(output_output))

[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


In [108]:
# Load the mnist (handwritten digits) dataset with one_hot encoding of pixels
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets(".", one_hot=True, reshape=False)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting .\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting .\train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting .\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting .\t10k-labels-idx1-ubyte.gz


In [109]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000218270B82E8>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x0000021825428860>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000218270B85F8>)

In [110]:
# Learning parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 128 # number of samples to process at a time
display_step = 1

n_input = 784 # mnist images are 28 * 28 pixels
n_classes = 10 # obviously there are 10 digit options

In [111]:
# Define the size of the hidden layer
n_hidden_layer = 256 # width of layer 

In [113]:
# Architecture of the neural network
weights = {
    'hidden_layer': tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}

biases = {
    'hidden_layer':tf.Variable(tf.random_normal([n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# Each row represents the weight of a given feature at each neuron
# Each column represents all the feature weights for a given neuron


In [114]:
# input 

x = tf.placeholder("float", [None, 28, 28, 1]) # features
y = tf.placeholder("float", [None, n_classes]) # labels

x_flat = tf.reshape(x, [-1, n_input]) # each row is one image

# MNIST images are one channel (grayscale)

In [115]:
x_flat.shape

TensorShape([Dimension(None), Dimension(784)])

In [117]:
# Architecture of neural network: one hidden layer and one out layer
# Using relu activation function for hidden layer
# y = xw + b

hidden_layer = tf.add(tf.matmul(x_flat, weights['hidden_layer']), biases['hidden_layer'])
hidden_output = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_output, weights['out']), biases['out'])

In [118]:
# Define loss function and optimizer

# cost function is softmax cross_entropy: measure of difference between
# predicted probability of class and actual class label

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=output, labels=y))

# the optimizer works to minimize the cost function using gradient descent
# need to specify a learning rate and call minimize method with a loss function
optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate).minimize(cost)

In [125]:
# initalize all the tensorflow variables with an initializer
init = tf.global_variables_initializer()
start_time = time.time()
save_file = "./model1.ckpt"
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init) # run the initializer for variables
    for e in range(training_epochs):
        total_batch = int(mnist.train.num_examples/batch_size) # number of batches
        for i in range(total_batch): 
            # MINST data set can be iterated through one batch at a time
            batch_x, batch_y = mnist.train.next_batch(batch_size) # iterate through batches of training data
            sess.run(optimizer, feed_dict={x:batch_x, y:batch_y}) # feed in appropriate data
    saver.save(sess, save_file)
end_time = time.time()
print("Training took {:.4f} seconds.".format(end_time - start_time))
        

Training took 77.6622 seconds.


In [121]:
import time
time.time()

1497379780.300505

In [127]:
bias

<tf.Variable 'Variable_3:0' shape=(10,) dtype=float32_ref>

In [130]:
# Loading model back in 

# first need to reset tf graph
tf.reset_default_graph()

weights = {
    'hidden_layer': tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}

biases = {
    'hidden_layer':tf.Variable(tf.random_normal([n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# input 

x = tf.placeholder("float", [None, 28, 28, 1]) # features
y = tf.placeholder("float", [None, n_classes]) # labels

x_flat = tf.reshape(x, [-1, n_input]) # each row is one image

# MNIST images are one channel (grayscale)

hidden_layer = tf.add(tf.matmul(x_flat, weights['hidden_layer']), biases['hidden_layer'])
hidden_output = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_output, weights['out']), biases['out'])

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=output, labels=y))

# the optimizer works to minimize the cost function using gradient descent
# need to specify a learning rate and call minimize method with a loss function
optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate).minimize(cost)

# tf.train.Saver is used to both save and restore tf models
saver = tf.train.Saver()

with tf.Session() as sess:
    saver.restore(sess, save_file)
    

INFO:tensorflow:Restoring parameters from ./model1.ckpt


InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256,10] rhs shape= [784,10]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1, save/RestoreV2_1)]]

Caused by op 'save/Assign_1', defined at:
  File "C:\Users\Will Koehrsen\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-130-85a2f09740b9>", line 37, in <module>
    saver = tf.train.Saver()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1056, in __init__
    self.build()
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [256,10] rhs shape= [784,10]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1, save/RestoreV2_1)]]


In [133]:
tf.reset_default_graph()

# example of saving a single layer model

from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

learning_rate = 0.001
n_input = 784
n_classes = 10

mnist = input_data.read_data_sets(".", one_hot=True)

features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

logits = tf.add(tf.matmul(features, weights), bias)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting .\train-images-idx3-ubyte.gz
Extracting .\train-labels-idx1-ubyte.gz
Extracting .\t10k-images-idx3-ubyte.gz
Extracting .\t10k-labels-idx1-ubyte.gz


In [139]:
import math

save_file = './model2.ckpt'
batch_size = 128
n_epochs = 100

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        # find total number of batches (must be an integet)
        batch_num = int(mnist.train.num_examples / batch_size)
        for batch in range(batch_num):
             # move to next batch of training examples
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict={features:batch_x, labels:batch_y})
            
        if epoch % 10 == 0:
            valid_accuracy = sess.run(accuracy, 
                                      feed_dict={features:mnist.validation.images, 
                                                 labels:mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy: {}'.format(epoch, valid_accuracy))
            
    saver.save(sess, save_file)

Epoch 0   - Validation Accuracy: 0.061799999326467514
Epoch 10  - Validation Accuracy: 0.2134000062942505
Epoch 20  - Validation Accuracy: 0.38119998574256897
Epoch 30  - Validation Accuracy: 0.47859999537467957
Epoch 40  - Validation Accuracy: 0.5540000200271606
Epoch 50  - Validation Accuracy: 0.6047999858856201
Epoch 60  - Validation Accuracy: 0.6449999809265137
Epoch 70  - Validation Accuracy: 0.6697999835014343
Epoch 80  - Validation Accuracy: 0.6926000118255615
Epoch 90  - Validation Accuracy: 0.7092000246047974


In [142]:
saver = tf.train.Saver()

with tf.Session() as sess:
    saver.restore(sess, save_file)
    test_accuracy = sess.run(accuracy, feed_dict = {features:mnist.test.images,
                                    labels:mnist.test.labels})
    
print('Test Accuracy : {}'.format(test_accuracy))
    

INFO:tensorflow:Restoring parameters from ./model2.ckpt
Test Accuracy : 0.724399983882904


In [143]:
weights.name

'Variable:0'

In [144]:
bias.name

'Variable_1:0'

In [158]:
# implementing dropout 

n_input = 784
n_classes = 10
n_hidden = 256


weights = {
    'hidden' : tf.Variable(tf.truncated_normal([n_input, n_hidden])),
    'out' : tf.Variable(tf.truncated_normal([n_hidden, n_classes]))
}

bias = {
    'hidden': tf.Variable(tf.zeros([n_hidden])),
    'out': tf.Variable(tf.zeros([n_classes]))
}

keep_prob = tf.placeholder(tf.float32)

hidden_layer = tf.add(tf.matmul(features, weights['hidden']), bias['hidden'])
hidden_output = tf.nn.relu(hidden_layer)
hidden_output = tf.nn.dropout(hidden_layer, keep_prob)

logits = tf.add(tf.matmul(hidden_layer, weights['out']), bias['out'])

In [159]:
keep_prob.name

'Placeholder_8:0'

In [160]:
weights['hidden']

<tf.Variable 'Variable_14:0' shape=(784, 256) dtype=float32_ref>

In [161]:
weights['out']

<tf.Variable 'Variable_15:0' shape=(256, 10) dtype=float32_ref>

In [168]:
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
bias = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

keep_prob = tf.placeholder(tf.float32) # will need to pass in value when running session

hidden_layer = tf.add(tf.matmul(features, weights[0]), bias[0])
hidden_layer = tf.nn.dropout(tf.nn.relu(hidden_layer), keep_prob)
# dropout takes layer and keep probability, units not kept are set to 0

output = tf.add(tf.matmul(hidden_layer, weights[1]), bias[1])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    logits = sess.run(output, feed_dict={keep_prob:0.5})
    
print(logits)

[[  2.98000002   7.54000044]
 [  0.91000009   1.01600003]
 [ 43.30000305  48.15999985]]
