In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

In [2]:
X = [[1,6], [2,4], [3,7], [6,8], [7,1], [8,4]]
y = [[7], [8], [16], [44], [50], [68]]

In [3]:
reg1_euc = KNeighborsRegressor(n_neighbors=1, metric = 'minkowski', p=2)

In [4]:
reg1_euc.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=1, p=2,
          weights='uniform')

In [5]:
reg1_euc.predict([[4,2]])

array([[ 8.]])

In [6]:
reg3_euc = KNeighborsRegressor(n_neighbors=3, metric = 'minkowski', p=2)
reg3_euc.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=2,
          weights='uniform')

In [7]:
reg3_euc.predict([[4,2]])

array([[ 42.]])

In [8]:
reg1_man = KNeighborsRegressor(n_neighbors=1, metric = 'minkowski', p=1)
reg1_man.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=1, p=1,
          weights='uniform')

In [9]:
reg1_man.predict([[4,2]])

array([[ 8.]])

In [10]:
reg3_man = KNeighborsRegressor(n_neighbors=3, metric = 'minkowski', p=1)
reg3_man.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=1,
          weights='uniform')

In [11]:
reg3_man.predict([[4,2]])

array([[ 24.66666667]])

In [12]:
reg3_euc_mod = KNeighborsRegressor(n_neighbors=3, weights='distance', metric = 'minkowski', p=2)
reg3_euc_mod.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=2,
          weights='distance')

In [13]:
reg3_euc_mod.predict([[4,2]])

array([[ 37.88396464]])

In [14]:
reg3_man_mod = KNeighborsRegressor(n_neighbors=3, weights='distance', metric = 'minkowski', p=1)
reg3_man_mod.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=1,
          weights='distance')

In [15]:
reg3_man_mod.predict([[4,2]])

array([[ 25.75]])

In [18]:
reg2_man = KNeighborsRegressor(n_neighbors=2, metric = 'minkowski', p=1)
reg2_man.fit(X,y)
reg2_man.predict([[4,2]])

array([[ 29.]])